apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: tomcatk8s
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      restartPolicy: Always
      containers:
      - name: spring-boot-app
        image: gstvo2k15/ultimate-cicd:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcat-war-storage
          mountPath: /usr/local/tomcat/webapps/
        envFrom:
        - configMapRef:
            name: spring-boot-config
        - secretRef:
            name: spring-boot-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        command: ["sh", "-c", "while true; do sleep 30; done"]
        # Liveness y Readiness probes deshabilitados temporalmente
      volumes:
      - name: tomcat-war-storage
        persistentVolumeClaim:
          claimName: tomcat-war-pvc
