apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: tomcatk8s
  labels:
    app: spring-boot-app
  # checkov:skip=CKV_K8S_14: Using latest image is intentional
  # checkov:skip=CKV_K8S_23: Running as root is required for this application
  # checkov:skip=CKV_K8S_8: Liveness probe is not needed at this moment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      # checkov:skip=CKV_K8S_29: SecurityContext is not needed for this application
      # checkov:skip=CKV_K8S_23: Running as root is required for application compatibility
      # checkov:skip=CKV_K8S_40: High UID is not needed    
      restartPolicy: Always
      containers:
      - name: spring-boot-app
        image: gstvo2k15/ultimate-cicd:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcat-war-storage
          mountPath: /usr/local/tomcat/webapps/
        envFrom:
        - configMapRef:
            name: spring-boot-config
        - secretRef:
            name: spring-boot-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        command: ["sh", "-c", "while true; do sleep 30; done"]
        # Liveness and Readiness probes disabled temporaly
        # checkov:skip=CKV_K8S_8: Liveness probe is not needed currently
        # checkov:skip=CKV_K8S_9: Readiness probe is not required at this time
        # checkov:skip=CKV_K8S_22: Read-only filesystem is not enforced
        # checkov:skip=CKV_K8S_20: Privilege escalation is required for app
        # checkov:skip=CKV_K8S_31: SeccompProfile is not configured intentionally
        # checkov:skip=CKV_K8S_35: Using env variables for secrets is required
        # checkov:skip=CKV_K8S_37: Container requires specific capabilities
        # checkov:skip=CKV_K8S_38: ServiceAccountToken auto-mount is required
        # checkov:skip=CKV_K8S_28: NET_RAW is required for network functions        
      volumes:
      - name: tomcat-war-storage
        persistentVolumeClaim:
          claimName: tomcat-war-pvc
