apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: tomcatk8s
  labels:
    app: spring-boot-app
  # checkov:skip=CKV_K8S_14: Using latest image is intentional
  # checkov:skip=CKV_K8S_43: Not using digest for image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      # checkov:skip=CKV_K8S_29: SecurityContext is not needed
      # checkov:skip=CKV_K8S_23: Running as root is required
      # checkov:skip=CKV_K8S_40: High UID is not necessary
      # checkov:skip=CKV_K8S_31: SeccompProfile is not enforced
      # checkov:skip=CKV_K8S_20: Privilege escalation is required
      # checkov:skip=CKV2_K8S_6: No NetworkPolicy is defined
      restartPolicy: Always
      containers:
      - name: spring-boot-app
        image: gstvo2k15/ultimate-cicd:latest
        securityContext:
          # checkov:skip=CKV_K8S_22: Read-only filesystem is not enforced
          # checkov:skip=CKV_K8S_8: Liveness probe is not needed
          # checkov:skip=CKV_K8S_9: Readiness probe is not needed
          # checkov:skip=CKV_K8S_35: Using env variables for secrets is required
          # checkov:skip=CKV_K8S_37: Specific capabilities are required
          # checkov:skip=CKV_K8S_38: ServiceAccountToken auto-mount is needed
          # checkov:skip=CKV_K8S_28: NET_RAW is required for networking
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcat-war-storage
          mountPath: /usr/local/tomcat/webapps/
        envFrom:
        - configMapRef:
            name: spring-boot-config
        - secretRef:
            name: spring-boot-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        command: ["sh", "-c", "while true; do sleep 30; done"]
      volumes:
      - name: tomcat-war-storage
        persistentVolumeClaim:
          claimName: tomcat-war-pvc
