apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-war-pvc
  namespace: tomcatk8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
