apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.nodePort }}
