services:
  tomcat-standalone:
    image: tomcat:9.0.102-jre8
    environment:
      - CATALINA_OPTS=-Xms256m -Xmx512m
    volumes:
      - tomcat-webapps:/usr/local/tomcat/webapps
    ports:
      - "8088:8080"

  tomcat-cluster-node1:
    image: tomcat:9.0.102-jre8
    environment:
      - CATALINA_OPTS=-Xms256m -Xmx512m
    volumes:
      - tomcat-webapps:/usr/local/tomcat/webapps
    networks:
      - tomcat-cluster

  tomcat-cluster-node2:
    image: tomcat:9.0.102-jre8
    environment:
      - CATALINA_OPTS=-Xms256m -Xmx512m
    volumes:
      - tomcat-webapps:/usr/local/tomcat/webapps
    networks:
      - tomcat-cluster

  nginx-load-balancer:
    image: nginx:1.27.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9080:80"
    networks:
      - tomcat-cluster

networks:
  tomcat-cluster:
    driver: bridge

volumes:
  tomcat-webapps:
