apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: tomcatk8s
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/gstvo2k15/tomcat.git
    targetRevision: fix/deployment
    path: spring-boot-app-manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
