apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/gstvo2k15/tomcat.git
    targetRevision: main
    path: spring-boot-app-manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
