apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: "email"
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
    receivers:
      - name: "email"
        email_configs:
          - to: "admin@example.com"
            from: "alertmanager@example.com"
            smarthost: "smtp.example.com:587"
            auth_username: "user"
            auth_password: "password"
            require_tls: true
    inhibit_rules:
      - source_matchers:
          - severity="critical"
        target_matchers:
          - severity=~"warning|info"
        equal: ["namespace", "alertname"]
