apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
data:
  prometheus.yaml: |
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - "prometheus-stack-kube-prom-alertmanager.monitoring.svc:9093"
