elasticsearch:
  enabled: true
  replicas: 1
  volumeSize: 10Gi
  heapSize: "1g"

logstash:
  enabled: true
  pipelineConfig: |
    input {
      beats {
        port => 5044
      }
    }
    filter {}
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
    }

kibana:
  enabled: true
  elasticsearchHost: "http://elasticsearch:9200"

ingress:
  enabled: true
  host: "elk.local"
  path: "/"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
